[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  BACKEND_URL = "http://178.117.208.226:8000"

[[redirects]]
  from   = "/api/*"
  to     = "http://178.117.208.226:8000/api/:splat"
  status = 200
  force  = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
